/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.client.ui;

/**
 *
 * @author ACER
 */
public class MainClientUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainClientUI.class.getName());

    /**
     * Creates new form MainServerUI
     */
    public MainClientUI() {
        initComponents();
        setupLogic();
    }
    
    private void setupLogic() {
        setLocationRelativeTo(null);
        try { com.formdev.flatlaf.FlatLightLaf.setup(); } catch (Exception e) {}
        lblTableInfo.setText("👤 Bàn số: " + cafe.client.NetworkManager.tableNumber);
        updateCartDisplay();
        
        class ScrollablePanel extends javax.swing.JPanel implements javax.swing.Scrollable {
            @Override public java.awt.Dimension getPreferredScrollableViewportSize() { return getPreferredSize(); }
            @Override public int getScrollableUnitIncrement(java.awt.Rectangle r, int o, int d) { return 20; }
            @Override public int getScrollableBlockIncrement(java.awt.Rectangle r, int o, int d) { return 20; }
            @Override public boolean getScrollableTracksViewportWidth() { return true; }
            @Override public boolean getScrollableTracksViewportHeight() { return false; }
        }
        ScrollablePanel responsivePanel = new ScrollablePanel();
        jScrollPane1.setViewportView(responsivePanel);
        
        cafe.client.UIHelper.loadMenuIntoPanel(responsivePanel, (item) -> {
            ItemDetailUI popup = new ItemDetailUI(this, true);
            popup.setItem(item, () -> updateCartDisplay());
            popup.setVisible(true);
        });
        
        btnSendOrder.addActionListener(e -> {
            if (!cafe.client.NetworkManager.isConnected()) {
                javax.swing.JOptionPane.showMessageDialog(this, "LỖI: Bạn chưa kết nối Server! Vui lòng chạy file LoginUI.java trước.");
                return;
            }
            cafe.client.NetworkManager.sendOrder();
            updateCartDisplay();
        });
    }
    
    private void updateCartDisplay() {
        StringBuilder sb = new StringBuilder();
        double total = 0;
        for (cafe.models.OrderItem orderItem : cafe.client.NetworkManager.cart) {
            sb.append(orderItem.toString()).append("\n");
            total += (cafe.client.UIHelper.getPrice(orderItem.getName()) * orderItem.getQty());
        }
        txtCart.setText(sb.toString());
        lblTotal.setText(String.format("Tổng tiền: %,.0f đ", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTableInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMenu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCart = new javax.swing.JTextArea();
        btnSendOrder = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quầy Order");

        lblTableInfo.setText("👤 Bàn số: ");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelMenu);

        txtCart.setColumns(20);
        txtCart.setRows(5);
        jScrollPane2.setViewportView(txtCart);

        btnSendOrder.setText("GỬI ORDER");

        lblTotal.setText("Tổng tiền: 0đ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTableInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTableInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainClientUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTableInfo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextArea txtCart;
    // End of variables declaration//GEN-END:variables
}
