/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.server.ui;

/**
 *
 * @author ACER
 */
public class MainServerUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainServerUI.class.getName());

    /**
     * Creates new form MainServerUI
     */
    public MainServerUI() {
        initComponents();
        setupLogic();
    }
    
    private void setupLogic() {
        setLocationRelativeTo(null);
        try { com.formdev.flatlaf.FlatLightLaf.setup(); } catch (Exception e) {}
        
        jTable1.setRowHeight(35);
        jTable1.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 16));
        jTable1.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
        
        // Khởi động Server ngầm
        new Thread(() -> {
            try {
                cafe.server.CafeServer.main(new String[0]);
            } catch (Exception ex) {}
        }).start();
        
        // Tự động làm mới bảng mỗi 1 giây
        new javax.swing.Timer(1000, e -> refreshTable()).start();
        
        btnPrepare.addActionListener(e -> updateSelectedOrder("PREPARING"));
        btnDone.addActionListener(e -> updateSelectedOrder("DONE"));
    }
    
    private void refreshTable() {
        int selectedRow = jTable1.getSelectedRow();
        String selectedOrderId = null;
        if (selectedRow >= 0) {
            selectedOrderId = jTable1.getValueAt(selectedRow, 0).toString();
        }
        
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        int newRowToSelect = -1;
        int rowIndex = 0;
        
        for (cafe.models.Order order : cafe.server.CafeServer.activeOrders.values()) {
            String itemsStr = "";
            for (cafe.models.OrderItem item : order.getItems()) {
                itemsStr += item.toString() + ", ";
            }
            model.addRow(new Object[]{
                order.getOrderId(),
                order.getTable(),
                itemsStr,
                cafe.models.MessageProtocol.translateStatus(order.getStatus())
            });
            
            if (String.valueOf(order.getOrderId()).equals(selectedOrderId)) {
                newRowToSelect = rowIndex;
            }
            rowIndex++;
        }
        
        if (newRowToSelect >= 0) {
            jTable1.setRowSelectionInterval(newRowToSelect, newRowToSelect);
        }
    }
    
    private void updateSelectedOrder(String newStatus) {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            try {
                int orderId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                cafe.models.Order order = cafe.server.CafeServer.activeOrders.get(orderId);
                if (order != null) {
                    order.setStatus(newStatus);
                    if (newStatus.equals("DONE")) {
                        cafe.server.CafeServer.activeOrders.remove(orderId);
                    }
                    
                    System.out.println("[SERVER UI] Đã cập nhật Đơn #" + orderId + " thành: " + cafe.models.MessageProtocol.translateStatus(newStatus));
                    
                    java.io.PrintWriter out = cafe.server.CafeServer.clientMap.get(order.getTable());
                    if (out != null) {
                        cafe.models.MessageProtocol.OrderStatusUpdateMessage msg = new cafe.models.MessageProtocol.OrderStatusUpdateMessage(orderId, newStatus);
                        out.print(cafe.models.MessageProtocol.toJson(msg));
                        out.flush();
                        System.out.println("[SERVER UI] Đã bắn thông báo về Bàn số " + order.getTable());
                    }
                }
            } catch (Exception ex) {}
            refreshTable();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 đơn hàng trên bảng!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblOrders = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPrepare = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quầy Pha Chế");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Đơn", "Bàn", "Món Ăn", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrders.setViewportView(jTable1);

        btnPrepare.setText("ĐANG PHA CHẾ");

        btnDone.setText("ĐÃ XONG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrepare, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tblOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrepare, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainServerUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnPrepare;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblOrders;
    // End of variables declaration//GEN-END:variables
}
